### PR TITLE
Enable DICE on Gimlet rot & create lab images

### PR DESCRIPTION
**Pull request by flihp**
Enables DICE our gimlet b & c builds. The new lab images configure DICE to create self-signed identity certs. Non-lab images configure DICE for the manufacturing process.

### CODE REVIEW

**Comment by labbott** [comment]
Are the Hubris images the same for the lab and not lab machines?

**Comment by flihp** [comment]
As part of this work I took a look at the existing toml inheritence mechanism from 61bf972e6a but it doesn't support the mechanisms we'd need (changing kernel features). Adding this to the implementation may be possible but it didn't seem like the right thing to do. I'm happy to do this work if reviewers think it's necessary.

**Comment by flihp** [comment]
> Are the Hubris images the same for the lab and not lab machines?

Yes. That might be necessary in the future but based on my work with @jclulow last week we only need a lab variant for stage0.

**Comment by labbott** [comment]
> As part of this work I took a look at the existing toml inheritence mechanism from [61bf972](https://github.com/oxidecomputer/hubris/commit/61bf972e6a91af25c79daac9cbe175373754002c) but it doesn't support the mechanisms we'd need (changing kernel features). Adding this to the implementation may be possible but it didn't seem like the right thing to do. I'm happy to do this work if reviewers think it's necessary.

It would be nice to have but I don't think it's necessary for this PR to merge. We might be looking at TOML alternatives long term anyway.

**Review by labbott — APPROVED** [review]
LGTM

**Pull request merged**
