### PR TITLE
Drop gdb file from the archive

### PR DESCRIPTION
**Pull request by labbott**
This file contains local paths which reduces reproducibility. The local paths also mean it's not useful in the archive anyway.

### CODE REVIEW

**Comment by mkeeter** [comment]
This will break `humility gdb` with

```
GDB script missing. Is your Hubris build too old?
```
(ironically)

Since it changes Humility compatibility, it should _technically_ be a Hubris version bump.  I don't feel too pedantic about it, though, since folks usually aren't using `humility gdb`; curious to hear other opinions.

Either way, we probably want a new `--gdb-script` argument to `humility gdb`, so it can either pull the script from the archive or use a local script.

**Comment by labbott** [comment]
I had forgotten `humility gdb` was even a thing (and here I was running it manually...). I'm inclined to let this break with an error message to pass the script in manually in humility.

**Comment by cbiffle** [comment]
As probably the main user of `humility gdb` at this point, I'd be comfortable updating the Humility error message to read

`GDB script missing; recent archives don't include it. Pass --gdb-script`

and not rev the archive version.

**Comment by cbiffle** [comment]
Better yet...

`GDB script missing; recent archives don't include it because humility gdb is deprecated, use xtask gdb`

**Comment by labbott** [comment]
https://github.com/oxidecomputer/humility/pull/510 associated humility change

**Review by mkeeter — APPROVED** [review]

**Comment by vchuravy** [comment]
I am playing around with hubris/humility for the first time and

```
cargo xtask gdb app/demo-stm32h7-nucleo/app-h753.toml
```

Terminates with a:
```
building crate demo-stm32h7-nucleo
    Finished `release` profile [optimized + debuginfo] target(s) in 0.35s
target/thumbv7em-none-eabihf/release/demo-stm32h7-nucleo -> target/demo-stm32h753-nucleo/dist/kernel
flash   = 0x08000000..0x08100000
ram     = 0x20000000..0x20020000
sram1_mac = 0x30000000..0x30010000
sram1   = 0x30010000..0x30020000
sram2   = 0x30020000..0x30040000
sram3   = 0x30040000..0x30048000
sram4   = 0x38000000..0x38010000
bank2   = 0x08100000..0x08200000
Used:
  flash:   0x311a0 (19%)
  ram:     0x1a300 (81%)
  sram1_mac: 0x4000 (25%)
  sram1:   extern region (jefe, dump_agent)
  sram2:   extern region (jefe, dump_agent)
  sram3:   extern region (jefe, dump_agent)
  sram4:   extern region (jefe, dump_agent)
  bank2:   0x0 (0%)
humility gdb failed: GDB script missing; recent archives don't include it. Pass --gdb-script or use xtask gdb
Error: humility failed
```

So I am using `xtask gdb`, yet the archive is not including the gdb script?
The error message is not clear in how to proceed from here.

**Pull request merged**
