### PR TITLE
Add updated bootleby

### PR DESCRIPTION
**Pull request by labbott**
This brings bootleby up to v1.3.0

### CODE REVIEW

**Review by flihp — COMMENTED** [review]
What's the relationship between these zip files and the existing bootleby bin files next to them? Like https://github.com/oxidecomputer/hubris/blob/99b7a384a7616831e1030c744603a008956bf9bd/app/oxide-rot-1/bootleby-oxide-rot-1-1.0.0.bartholomew.bin

**Comment by flihp** [comment]
The merge commit here should probably be rebased away too?

**Comment by labbott** [comment]
> What's the relationship between these zip files and the existing bootleby bin files next to them? Like https://github.com/oxidecomputer/hubris/blob/99b7a384a7616831e1030c744603a008956bf9bd/app/oxide-rot-1/bootleby-oxide-rot-1-1.0.0.bartholomew.bin

That's a single binary suitable for writing directly to memory (e.g. `lpc55_flash write-memory 0x0`). I don't think we've kept that up to date. I can just remove it since if you really want the single binary you can grab the bootleby bundle and unzip.

**Comment by flihp** [comment]
Thanks for pulling those old bootleby images. Keeping those around is just inviting confusion.

**Pull request merged**
