### PR TITLE
gimlet-seq: record sequencer T6 state on power off

### LINKED ISSUE #1648: gimlet: capture sequencer T6 state on power off
There are several occasions when the T6 fails to come up successfully and therefore is powered off. When this happens it'd be helpful if the sequencer task captured and at the minimum right now tossed in the ringbuf as data for the power off transition prior to issuing the command to the sequencer. I think the registers we want are:

* `IFR`
* `NIC_CTRL`
* `NIC_STATUS`
* `OUT_STATUS_NIC1`
* `OUT_STATUS_NIC2`
* `AMD_STATUS`

I believe these'll help us understand where this is going on and how it fails.

### PR DESCRIPTION
**Pull request by hawkw**
As described in #1648, when the NIC fails to come up successfully and is
powered off, it's desirable to capture sequencer register state
associated with the NIC and stick them in the ringbuf before actually
commanding the sequencer to power off the NIC, in order to debug NIC
failures.

This branch changes the `gimlet-seq-server` task to record the values of
the `NIC_CTRL`, `NIC_STATUS`, `OUT_STATUS_NIC1` and `OUT_STATUS_NIC2`
registers in the ringbuf when `NIC_PWREN_L` is asserted high while in
the `A0PlusHP` state. Issue #1648 also requested that the `IFR` and
`AMD_STATUS` registers be recorded in the ringbuf when this occurs, but
those registers should already be present in the `Trace::Status` entry
that's recorded every time the sequencer task handles a notification,
immediately prior to checking if the task must transition the NIC's
state. So, I chose not to add additional ringbuf events for those
registers to avoid pushing other stuff off the end of the ringbuf.

Fixes #1648

### CODE REVIEW

**Comment by rmustacc** [comment]
Is it easy for you to provide an example of the ringbuf data? This should be generated natively by booting the gimlet and the t6init service.

**Comment by hawkw** [comment]
> Is it easy for you to provide an example of the ringbuf data? This should be generated natively by booting the gimlet and the t6init service.

Sure, one moment!

**Comment by hawkw** [comment]
If you think it would be useful, we can also record the NIC registers _any_ time `NIC_PWREN_L` changes, rather than just when going high in the `A0PlsuHP` state?

**Review by cbiffle — APPROVED** [review]

**Review by rmustacc — APPROVED** [review]
Thanks for this, @hawkw.

> If you think it would be useful, we can also record the NIC registers any time NIC_PWREN_L changes, rather than just when going high in the A0PlsuHP state?

I don't think (famous last words), it's really necessary. The main thing we need when we're powering it off is whether or not we thought it successfully got out of reset. Realistically longer term (and not now) if we try to "power on" the nic aka clear reset because all the power is already on, then we shouldn't even proceed if we don't have power good and handwave handwave, generate an alert and trigger the power fault signals. But that's stuff for another time.

**Pull request merged**
