### PR TITLE
Update QSFP FPGA image

### PR DESCRIPTION
**Pull request by Aaron-Hartwig**

### CODE REVIEW

**Comment by mkeeter** [comment]
Pending further debug, as MDIO isn't happy (??)

**Comment by mkeeter** [comment]
Specifically, we're seeing the `monorail` task fail to configure the VSC8562 on the front IO board.

It crashes with:
```
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
system time = 1233184
ID TASK                 GEN PRI STATE
13 monorail              21   6 FAULT: panicked at 'Could not initialize BSP: BadPhyPatchPort(31)', task/monorail-server/src/main.rs:61:13 (was: ready)
   |
   +--->  0x24016e40 0x080514d6 userlib::sys_panic_stub
                     @ /hubris/sys/userlib/src/lib.rs:992
          0x24016e78 0x0805150e userlib::sys_panic
                     @ /hubris/sys/userlib/src/lib.rs:984
          0x24016e78 0x08051512 rust_begin_unwind
                     @ /hubris/sys/userlib/src/lib.rs:1300
          0x24016e98 0x0804e71a core::panicking::panic_fmt
                     @ /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/core/src/panicking.rs:127
          0x24017000 0x0804c004 main
                     @ /hubris/task/monorail-server/src/main.rs:32
```

The `monorail` ringbuf is more helpful:
```
humility: ring buffer vsc85xx::__RINGBUF in monorail:
 NDX LINE      GEN    COUNT PAYLOAD
   2  133        1        1 GotCrc(0x16d6)
   3   89        1        1 PatchState { patch_ok: false, skip_download: false }
   4  133        1        1 GotCrc(0x29e8)
   5   18        1        1 AtomPatchSuspend(true)
   6   35        1        1 AtomPatchResume(false)
   7   84        1        1 Vsc8504Init(0x5)
   8   18        1        1 AtomPatchSuspend(true)
   9   35        1        1 AtomPatchResume(false)
  10   84        1        1 Vsc8504Init(0x6)
  11   18        1        1 AtomPatchSuspend(true)
  12   35        1        1 AtomPatchResume(false)
  13   84        1        1 Vsc8504Init(0x7)
  14   18        1        1 AtomPatchSuspend(true)
  15   35        1        1 AtomPatchResume(false)
   0   79        2        1 Vsc8562InitQsgmii(0x0)
   1   23        2        1 ViperPatch(0x0)
```
i.e. it's failing [here](https://github.com/oxidecomputer/hubris/blob/07bfc3360741115b76ac5c5bb42406afc889a8e1/drv/vsc85xx/src/viper.rs#L69)

--------------------------------------------------------------------------------

Here's an annotated ringbuf of SPI communication to the front IO FPGA1:

Write 0x1 to the page selection register (0x1f)
```
  34  286      770        1 Start(write, (0x3, 0x0))
  35  404      770        2 Tx(0x0)
  36  404      770        1 Tx(0x13)
  37  438      770        3 Rx(0x0)
  38  286      770        1 Start(write, (0x7, 0x0))
  39  404      770        3 Tx(0x0)
  40  404      770        1 Tx(0x1)
  41  404      770        1 Tx(0x0)
  42  404      770        1 Tx(0x1f)
  43  404      770        1 Tx(0x3)
  44  438      770        7 Rx(0x0)
```
Read PHY_SMI_STATUS
```
  45  286      770        1 Start(write, (0x3, 0x0))
  46  404      770        1 Tx(0x1)
  47  404      770        1 Tx(0x0)
  48  404      770        1 Tx(0x12)
  49  438      770        3 Rx(0x0)
  50  286      770        1 Start(read, (0x0, 0x1))
  51  404      770        1 Tx(0x0)
  52  438      770        1 Rx(0x0)
```
Read PHY register 0x17
```
  53  286      770        1 Start(write, (0x3, 0x0))
  54  404      770        2 Tx(0x0)
  55  404      770        1 Tx(0x13)
  56  438      770        3 Rx(0x0)
  57  286      770        1 Start(write, (0x7, 0x0))
  58  404      770        5 Tx(0x0)
  59  404      770        1 Tx(0x17)
  60  404      770        1 Tx(0x2)
  61  438      770        7 Rx(0x0)
```

Read PHY_SMI_STATUS (0x12)
```
  62  286      770        1 Start(write, (0x3, 0x0))
  63  404      770        1 Tx(0x1)
   0  404      771        1 Tx(0x0)
   1  404      771        1 Tx(0x12)
   2  438      771        3 Rx(0x0)
   3  286      771        1 Start(read, (0x0, 0x1))
   4  404      771        1 Tx(0x0)
   5  438      771        1 Rx(0x0)
```
Prepare to read from RDATA_H/L
```
   6  286      771        1 Start(write, (0x3, 0x0))
   7  404      771        1 Tx(0x1)
   8  404      771        1 Tx(0x0)
   9  404      771        1 Tx(0x13)
  10  438      771        3 Rx(0x0)
```
Execute that read
```
  11  286      771        1 Start(read, (0x0, 0x2))
  12  404      771        2 Tx(0x0)
  13  438      771        2 Rx(0xff)
```

This all looks reasonable until the last read, which reads `0xffff`.

--------------------------------------------------------------------------------

However, manually instructing the FPGA to read register 31, it looks like we're not on page 1:
```console
matt@niles ~ (sidecar) $ h spi -p1 -D1 --write 0x0,0x0,0x17,0,31,2
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
humility: SPI master is spi1_driver
[Ok([])]
matt@niles ~ (sidecar) $ h spi -p1 -D1 --write 0x1,0x0,0x13 --read --nbytes=5 --discard 3
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
humility: SPI master is spi1_driver
             \/  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
0x00000000 | 00 00        
```

Sure enough, reading the ID register gives the expected `0x707e1`, meaning (a) PHY communications works when commanded manually through Humility and (b) we're on page 0:
```console
matt@niles ~ (sidecar) $ h spi -p1 -D1 --write 0x0,0x0,0x17,0,0x02,2
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
humility: SPI master is spi1_driver
[Ok([])]
matt@niles ~ (sidecar) $ h spi -p1 -D1 --write 0x1,0x0,0x13 --read --nbytes=5 --discard 3
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
humility: SPI master is spi1_driver
             \/  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
0x00000000 | 00 07                                           | ..
matt@niles ~ (sidecar) $ h spi -p1 -D1 --write 0x0,0x0,0x17,0,0x03,2
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
humility: SPI master is spi1_driver
[Ok([])]
matt@niles ~ (sidecar) $ h spi -p1 -D1 --write 0x1,0x0,0x13 --read --nbytes=5 --discard 3
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
humility: SPI master is spi1_driver
             \/  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
0x00000000 | 07 e1                                           | ..
```

**Comment by mkeeter** [comment]
For completeness, here's an example of me doing the same stuff through the FPGA Idol API, instead of manually via SPI.

--------------------------------------------------------------------------------

Here's me reading the ID of the FPGA:
```
matt@niles ~ (sidecar) $ h hiffy -t ecp5_front_io -c Fpga.user_design_read_reg -adevice_index=1,addr=0
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
Fpga.user_design_read_reg() => 0x1
matt@niles ~ (sidecar) $ h hiffy -t ecp5_front_io -c Fpga.user_design_read_reg -adevice_index=1,addr=1
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
Fpga.user_design_read_reg() => 0xde
matt@niles ~ (sidecar) $ h hiffy -t ecp5_front_io -c Fpga.user_design_read_reg -adevice_index=1,addr=2
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
Fpga.user_design_read_reg() => 0xaa
matt@niles ~ (sidecar) $ h hiffy -t ecp5_front_io -c Fpga.user_design_read_reg -adevice_index=1,addr=3
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
Fpga.user_design_read_reg() => 0x55
```

Okay, let's try reading the ID of the PHY:
```
# Set PHY_SMI_REG_ADDR = 2 ("identifier 1")
h hiffy -t ecp5_front_io -c Fpga.user_design_write_reg -adevice_index=1,addr=24,op=Write,value=2

# Trigger the read by writing to `PHY_SMI_CTRL`
h hiffy -t ecp5_front_io -c Fpga.user_design_write_reg -adevice_index=1,addr=25,op=Write,value=2

# Read back data:
h hiffy -t ecp5_front_io -c Fpga.user_design_read -adevice_index=1,addr=19 --num=2
```

This correctly returns the "Identity 1" PHY register
```
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
Fpga.user_design_read() => ()
Data: [0, 7]
```
... do the same for the `Identifier 2` register on the PHY, and we get
```
matt@niles ~ (sidecar) $ h hiffy -t ecp5_front_io -c Fpga.user_design_read -adevice_index=1,addr=19 --num=2 -x
humility: attached to 0483:374f:002A001C4D46500F20373033 via ST-Link V3
Fpga.user_design_read() => ()
Data: [7, e1]
```

This all looks correct.

Let's try modifying the page selection register.

Set `PHY_SMI_WDATA_H/L` to [0, 1], so the PHY will switch to page 1
```
h hiffy -t ecp5_front_io -c Fpga.user_design_write_reg -adevice_index=1,addr=21,op=Write,value=0
h hiffy -t ecp5_front_io -c Fpga.user_design_write_reg -adevice_index=1,addr=22,op=Write,value=1
```

Select PHY register 31
```
h hiffy -t ecp5_front_io -c Fpga.user_design_write_reg -adevice_index=1,addr=24,op=Write,value=31
```

Trigger the actual write
```
h hiffy -t ecp5_front_io -c Fpga.user_design_write_reg -adevice_index=1,addr=25,op=Write,value=3
```

Now, we can read back PHY register 24 / 0x17
```
h hiffy -t ecp5_front_io -c Fpga.user_design_write_reg -adevice_index=1,addr=24,op=Write,value=0x17
h hiffy -t ecp5_front_io -c Fpga.user_design_write_reg -adevice_index=1,addr=25,op=Write,value=2
h hiffy -t ecp5_front_io -c Fpga.user_design_read -adevice_index=1,addr=19 --num=2
```

=> `Data: [0, 0]`

This seemed to work fine, and it's returning the correct values.

--------------------------------------------------------------------------------

This suggests that maybe something goes wrong when we do these transactions _too fast_?

**Comment by Aaron-Hartwig** [comment]
@mkeeter I updated the PR with a [bitfile from Buildomat](https://buildomat.eng.oxide.computer/wg/0/artefact/01GDJZP1YR9P0RP0QWVZHF6822/UOPBE4dlHHWrlPPQkFAixxuaSdzMzOAuajF9IVkE58gQuOO7/01GDJZPGFQ9THBDVGSR0C2HC91/01GDK06JWWTY3KKF4SMNRF9J4P/qsfp_x32.bit) that was generated from the actual commit for the fix.

**Pull request merged**
